name: CI
on:
  pull_request:
  push:
    branches: main

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test (${{matrix.elixir}}/${{matrix.otp}})

    strategy:
      matrix:
        otp: [25.x, 26.x, 27.x]
        elixir: [1.15.x, 1.16.x, 1.17.x]

    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          deps
        key: ${{ runner.os }}-mix-${{matrix.otp}}-${{matrix.elixir}}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{matrix.otp}}-${{matrix.elixir}}-

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: mix deps.get

    - name: Run Tests
      run: mix test

  formatter:
    runs-on: ubuntu-latest
    name: Formatter (1.17.x/27.x)

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: 27.x
        elixir-version: 1.17.x
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-27-1.17-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-27-1.17-

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: mix deps.get

    - name: Run Formatter
      run: mix format --check-formatted
